### ISSUE TITLE
Feature: swipe to modify category name

### ISSUE THREAD

**Issue by kiennguyenchi** [mikaelacaron/brain-marks#100]
**Is your feature request related to a problem? Please describe.**
I can see that when users have some categories. They can swipe and choose to delete the category. What if user wants to modify the name of the category.

**Describe the solution you'd like**
I want to implement swipe action for the category, that also shows **Edit Button** next to existing **Delete Button** right now to modify the name of category.

**Comment by kiennguyenchi** [comment]
Hi @mikaelacaron, I would like to work on this new feature. What do you think?

**Comment by mikaelacaron** [comment]
Hi @kiennguyenchi this exists!
Press and hold on the row and a context menu pops up for editing

**Comment by kiennguyenchi** [comment]
Should we change it to swipe action? Because holding the row like that seems not interactive to the user.

**Comment by mikaelacaron** [comment]
At the moment I don't want to change it. I originally designed it after the Apple Notes app, and that's the interaction that they use for this action

**Comment by kiennguyenchi** [comment]
Okay I see, I will propose another feature.
