### ISSUE TITLE
BUG when in the process of deleting a category.

### ISSUE THREAD

**Issue by AC40** [mikaelacaron/brain-marks#105]
**Describe the bug**
Visual glitch when deleting a category and opening the `CategorySheetView`

**To Reproduce**
1. Create at least one Category
2. Swipe to make the delete option appear trailing behind the category
3. Do not click it
4. Tap the + in the top leading corner to show `CategorySheetView`
5. Dismiss the `CategorySheetView` in any way
6. Bug: A read minus appears in-front of the category's icon. The Category is not tappable, meaning the tweet collection is not reachable.

**Expected behavior**
The Categories are shown as they usually are, without a read minus button next to them. Categories are tappable.

**Screenshots**
![Screenshot 2021-12-15 at 18 48 21](https://user-images.githubusercontent.com/81184358/146238585-a7181abc-7018-4a23-b808-f87168d624fa.jpg)
![Screenshot 2021-12-15 at 18 48 34](https://user-images.githubusercontent.com/81184358/146238595-8c2d4fcf-82d5-4f0c-84f0-321f6297bf7f.jpg)

https://user-images.githubusercontent.com/81184358/146238466-8752b065-4bd7-41ea-a896-e01704b8fc93.mov

**Smartphone (please complete the following information):**
 - Device: [iPhone 12 mini, Simulator iPhone 13, Simulator iPad Pro (5th Gen.)]
 - OS: [iOS 15]
 - App Version [Version 1.1]

**Additional context**
This bug is not present on the apps AppStore version, only on current Dev branch...

**Comment by AC40** [comment]
This bug will be resolved after feature #67 will be implemented, since this has to do with then environment variable `editMode` and will be automatically fixed when implementing a reordering functionality.

**Comment by mikaelacaron** [comment]
I no longer see this bug in iOS 16.0, so I'm going to close the issue for now.
I'm preparing for Hacktoberfest 22
