### ISSUE TITLE
Add Localizable Strings to Empty Screens

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#107]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The empty category and empty tweet strings aren't localized into German and English (they were accidentally missed).

Create and use the Localizable Strings

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Astefani21** [comment]
Hey, could I help out on this?
