### ISSUE TITLE
BUG: TextField is squashed when creating a category

### ISSUE THREAD

**Issue by AC40** [mikaelacaron/brain-marks#110]
**Describe the bug**
When creating a category, on small devices there is a chance the TextField gets pushed behind the NavigationTitle

**To Reproduce**
1. Click on the leading button to create a new Category
2. Tap on the TextField so your Keyboard pops up

**Expected behavior**
There are two ways to solve this (or others, but those are the two I thought of):
Either you wrap the icons into a `ScrollView`, so on small devices the user simply scrolls down to the other icons.
Or the space between the icons is reduced.

**Screenshots**
![IMG_1628](https://user-images.githubusercontent.com/81184358/146808773-b31ec7cd-df9a-4548-8ecc-74923b90671d.PNG)
ble, add screenshots to help explain your problem

https://user-images.githubusercontent.com/81184358/146808803-23875f7a-8dbf-4281-ad0f-4ddf1819732b.mov

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 mini, iPhone 13 mini simulator]
       - This bug appears only on "mini" devices (12 and 13) as far as I could tell
 - OS: [iOS 15]
 - App Version [v.1.1 (current Dev branch)]

**Additional context**
I would tend towards option one, as it is way more scalable and will work when adding more icons or even smaller devices, while two is just a temporary fix.

**Comment by AC40** [comment]
I would like to work on this issue.

**Comment by mikaelacaron** [comment]
When I had tried this on my simulator I saw this also happened on iPhone 13
