### ISSUE TITLE
Replace all print commands to the console with Apple's unified logging system

### ISSUE THREAD

**Issue by byaruhaf** [mikaelacaron/brain-marks#129]
**Is your feature request related to a problem? Please describe.**
update from print command to Apple's unified logging system

**Describe the solution you'd like**
Replace all print commands to the console with Apple's unified logging system

**Comment by byaruhaf** [comment]
Please assign me to this issue, if the issue is approved.

**Comment by WDI-Json** [comment]
Can I pick this up?

**Comment by mikaelacaron** [comment]
Closed with #147
