### ISSUE TITLE
FEATURE: Add alternate app icons 

### ISSUE THREAD

**Issue by SuzGupta** [mikaelacaron/brain-marks#130]
**Is your feature request related to a problem? Please describe.**
I get bored when an app only has one icon. I love choices!

**Describe the solution you'd like**
I'd like to see alternate app icons.

**Describe alternatives you've considered**
Honestly, I have not yet considered other options because I think alternative app icons are super fun and fairly straightforward. Really, this is primarily a design issue. 

Here's the Apple doc on how to do this: https://developer.apple.com/documentation/xcode/asset_management/configuring_your_app_to_use_alternate_app_icons

**Additional context**

**Comment by k-stannard** [comment]
I'd like to work on this!

**Comment by mikaelacaron** [comment]
You got it! you can also convert it to use a single asset rather than needing all the different sizes (I think that's an Xcode 14 thing), but please correct me if I'm wrong

**Comment by k-stannard** [comment]
> You got it! you can also convert it to use a single asset rather than needing all the different sizes (I think that's an Xcode 14 thing), but please correct me if I'm wrong

Sweet, thanks Mikaela! I will look into that! Also, does this issue qualify for Hacktoberfest?

**Comment by mikaelacaron** [comment]
@k-stannard yes! forgot the tag 👻

**Comment by mikaelacaron** [comment]
Closed with #153

**Comment by SuzGupta** [comment]
@k-stannard I love these icons, so fun!!
