### ISSUE TITLE
Update Copy on Settings View

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#133]
**Describe the solution you'd like**
* Update the copy on the `SettingsView`, be sure to update the German localization.
* See the `Localization` files: `BrainMarksIsOpenSource...` and `IfYouWantToContribute`
* Also please change the key `BrainMarksIsOpenSource...` to not have 3 dots

* First Block
```
Brain Marks is an open source project! It was created during the Big Brain Hackathon and has continued to be open sourced for Hacktoberfest.
You can categories your saved tweets.
```
* Second Block
```
You can contribute to this project!
This project is open source on GitHub. Visit the link below to contribute. We have a list of all contributors, your name could be there!
```

**Describe alternatives you've considered**

**Additional context**
* Current copy in the first block
<img width="336" alt="Screen Shot 2022-10-01 at 6 35 55 PM" src="https://user-images.githubusercontent.com/22946902/193430756-6fbd5cf4-9afb-4779-b72a-f79688e7391a.png">

* Current copy in the second block
<img width="328" alt="Screen Shot 2022-10-01 at 6 34 16 PM" src="https://user-images.githubusercontent.com/22946902/193430734-657f674c-8a49-429e-9584-cd8746a7db90.png">

**Comment by Drag0ndust** [comment]
May I take this issue?
