### ISSUE TITLE
Analytics Ideas

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#138]
## Describe the feature you want the app to have that it currently doesn't
* What kind of frameworks can I add to the app to track what versions users are on?
* Also interested in tracking events, like people saving tweets (not the actual content, but just events)

## Describe alternatives you've considered
* I'm open to any options that are available via SPM

## Additional context
* Interesting in any ideas, but I'm going to implement this myself, most likely

**Comment by heyjaywilson** [comment]
Are you also wanting identifiable sessions? So a user's ID is assigned to an event or events that they do or just want to keep track of "save tweet tapped on {date}"?

**Comment by heyjaywilson** [comment]
I've been on projects that used [Segment](https://segment.com) to feed into other analytics platforms including GA or a custom database. You can install the SDK via SPM and then send it to a platform that doesn't have SPM support if you are leaning towards one that doesn't.

**Comment by mikaelacaron** [comment]
> Are you also wanting identifiable sessions? So a user's ID is assigned to an event or events that they do or just want to keep track of "save tweet tapped on {date}"?

I'm open to either, if there's a big reason for one or the other I'd love to hear it.

I'm leaning on using [Telemetry Deck](https://telemetrydeck.com)

**Comment by haIIux** [comment]
I see this issue has not been assigned, has anyone claimed this issue to tackle? Aside from the items in the issue post, do you have any additional items you'd like to log?

**Comment by mikaelacaron** [comment]
Not at the moment, but I'm kinda leaning on doing this one myself, because I have a huge bug 🐛  to fix, and I might add this at the same time to know how many people update to the new version

**Comment by haIIux** [comment]
> Not at the moment, but I'm kinda leaning on doing this one myself, because I have a huge bug 🐛  to fix, and I might add this at the same time to know how many people update to the new version

Okay! Sounds good, I'll poke around for another issue to tackle.

**Comment by mikaelacaron** [comment]
I'm adding [Telemetry Deck](https://dashboard.telemetrydeck.com/) and fixing a bug, to be able to have a better idea of what version users are on, before submitting all the changes from Hackoberfest
