### ISSUE TITLE
SwiftUI Optimization Use toolbar modifier

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#139]
## Describe the feature you want the app to have that it currently doesn't
* Replace `navigationBarItems` on `AddURLView` with the `.toolbar` modifier instead using `ToolbarItem`
* Replace others if needed

## Describe alternatives you've considered
* N/A

## Additional context
* N/A

**Comment by Miablo** [comment]
May I be assigned this issue?

**Comment by mikaelacaron** [comment]
@Miablo I assigned #139, I'm going to limit it to one issue at a time for now

**Comment by haIIux** [comment]
May I be assigned to this please?

**Comment by mikaelacaron** [comment]
@haIIux Someone is already assigned to this issue

**Comment by haIIux** [comment]
> 

Ah. Just seing that now I need more coffee!
