### ISSUE TITLE
REFACTOR - Async / Await

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#141]
## Describe the feature you want the app to have that it currently doesn't
* Refactor and use async / await syntax for fetching a tweet

## Describe alternatives you've considered
* N/A

## Additional context
* In `AddURLViewModel.swift` in the function `fetchTweet` change the function to use async / await syntax

**Comment by rashmisubhash** [comment]
Can I take this up?

**Comment by Drag0ndust** [comment]
I can help here if you want @rashmisubhash  and @mikaelacaron

**Comment by mikaelacaron** [comment]
@rashmisubhash and @Drag0ndust you're welcome to collaborate! I'm not sure how it works with Hacktoberfest and if the PR will count for you both

**Comment by Drag0ndust** [comment]
Now everything should be fine @mikaelacaron
