### ISSUE TITLE
FEATURE - Small Widget - Create New Tweet

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#142]
## Describe the feature you want the app to have that it currently doesn't
* Widgets! 😍 
* Create a small widget for adding a new tweet

## Describe alternatives you've considered
* I'm open to ideas for any widgets of any size

## Additional context
* Tapping on the widget brings you to the `AddURLView` for pasting a tweet link and choosing a category

**Comment by SuzGupta** [comment]
I'd like to try this one next please.

**Comment by mikaelacaron** [comment]
You got it! Wait until I merge #156

**Comment by SuzGupta** [comment]
Thanks, hopefully tomorrow🤞

**Comment by mikaelacaron** [comment]
Closed with PR #167
