### ISSUE TITLE
FEATURE - Small Widget - Create a New Category

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#143]
## Describe the feature you want the app to have that it currently doesn't
* Widgets! 😍 
* Create a small widget for adding a new category

## Describe alternatives you've considered
* I'm open to ideas for any widgets of any size

## Additional context
* Tapping on the widget brings you to the `CategorySheetView` for creating a new category

**Comment by SuzGupta** [comment]
@mikaelacaron can I try this one please?

**Comment by SuzGupta** [comment]
I've gotten part of the way there on this but need help figuring out the deep linking part. I've got a draft PR open here: https://github.com/mikaelacaron/brain-marks/pull/156 . Would welcome advice!
