### ISSUE TITLE
BUG - Shouldn't need to reselect prefilled category

### ISSUE THREAD

**Issue by SuzGupta** [mikaelacaron/brain-marks#144]
## Describe the bug
When adding a tweet link, the category field is automatically populated with the first category created, which is fine (although maybe should be the most recently created category). However, the app doesn't seem to know that and then wants you to select a category again.
## To Reproduce
1. Add one or more categories
2. Add a tweet link
3. Tap Save
4. Uh oh alert displays saying you must select a category

## Expected behavior
* After tapping Save, return to the Category list view. If you then navigate to the category in which you added the link, the linked tweet should display.

## Screenshots
* ![RequestingCategoryButItsThere](https://user-images.githubusercontent.com/5115383/193488181-82e03e48-064e-4337-a0f9-75514f1320f6.png)
## Device Info (please complete the following information):
 * Device: iPhone14 Pro simulator
 * OS: iOS 16.0
 * App Version: 1.1?

## Additional Context

From discussion with @mikaelacaron, "pretty sure it’s due to iOS 16, cause it used to link you to a new list, and push a new view, but now the context menu instead comes up"

**Comment by SuzGupta** [comment]
@mikaelacaron Changed my mind... please do assign me, although right now I have no idea how to fix this 😆

**Comment by mikaelacaron** [comment]
No worries! Neither do I 😂

**Comment by SuzGupta** [comment]
@mikaelacaron looking into this a little, `AddURLView()` shows the alert when `selectedCategory.name` is an empty string. I added a print statement to learn a little more. Both that and the "Got single category" print aren't working as expected:

```
✅ Got single category: nil
✅ Got single category: nil
Picker: the selection "AWSCategory(id: "69D8E3D4-3FC6-4E9C-85B9-9C97C42600B6", name: "", imageName: Optional("folder"), tweets: Optional(Amplify.List<brain_marks.AWSTweet>), categoryThumbnail: nil)" is invalid and does not have an associated tag, this will give undefined results.
Picker: the selection "AWSCategory(id: "69D8E3D4-3FC6-4E9C-85B9-9C97C42600B6", name: "", imageName: Optional("folder"), tweets: Optional(Amplify.List<brain_marks.AWSTweet>), categoryThumbnail: nil)" is invalid and does not have an associated tag, this will give undefined results.
```
I'm wondering if I should wait until you kill off AWSAmplify and see if that resolves this issue. What do you think?

**Comment by mikaelacaron** [comment]
hmmmm, that's interesting the category name is empty, the model will still look the same as `AWSCategory` as the new one that I'll be making, but maybe it'll be best to wait until AWS is gone

**Comment by SuzGupta** [comment]
The category name shouldn't be seen as empty there though (for example, in the screencap above, we see the category name "Education Generally") which makes me wonder if it's better to wait until AWS is gone. If so, may I pick another issue? Sorry for the assigning/unassigning hassle :/

**Comment by mikaelacaron** [comment]
No worries!

**Comment by Drag0ndust** [comment]
I can have a look, if you like
