### ISSUE TITLE
FEATURE - RequestBuilder

### ISSUE THREAD

**Issue by Drag0ndust** [mikaelacaron/brain-marks#150]
## Describe the feature you want the app to have that it currently doesn't
*  Create a RequestBuilder for creating URLRequests in AddURLViewModel
* and maybe also in other places of the app

**Comment by Drag0ndust** [comment]
I can work on this issue and also create Unit tests for it.

@mikaelacaron If it is ok, please add the hacktoberfest label and assign me ;)

**Comment by mikaelacaron** [comment]
What are you looking for in a Request Builder? Can you elaborate on what that is?

**Comment by Drag0ndust** [comment]
Actually it's just encapsulating some functions in a separate object to make the code more testable and remove the code from the viewmodel.
Will open a PR later, then you can decide if you want it or not 😉
