### ISSUE TITLE
BUG - Invalid API access from background thread

### ISSUE THREAD

**Issue by DominatorVbN** [mikaelacaron/brain-marks#171]
## Describe the bug
* Codebase contains multiple invalid API access code paths either publishing or accessing unsupported API from background threads

## To Reproduce
1. Go to 'Create category
2. Add a new category
3. Repeat above steep for 5-10 time
4. See error in the Xcode console

## Expected behavior
* There should be no invalid access occurring, this could lead to unpredicted behaviors in app

## Screenshots
<img width="756" alt="Screenshot 2022-10-27 at 3 54 01 AM" src="https://user-images.githubusercontent.com/41822551/198150407-688ec8ac-6bc0-4bbc-b5be-b0cda49605ee.png">

## Device Info (please complete the following information):
 * Device: [iPhone14 Pro Simulato]
 * OS: [ iOS 16.1]
 * App Version [v1.1]

**Comment by MikesHorcrux** [comment]
Ill take a look at this bug and see if I can fix/ reproduce

**Comment by MikesHorcrux** [comment]
@mikaelacaron  I keep getting 

`2022-10-29 11:55:19.613688-0500 brain-marks[21129:2679872] [Networking] ❌ Status code is 401`

when trying to save a tweet I have my twitter api key in my secrets and still no go. am I missing something ?

**Comment by MikesHorcrux** [comment]
was able to reproduce this error but not with creating a category, this errors stems from the contribution view. 

screen shot below 
![Screenshot 2022-10-29 at 5 18 25 PM](https://user-images.githubusercontent.com/53712873/198854420-4637507a-2dbe-4bc6-b692-63d140db7dd9.png)

**Comment by mikaelacaron** [comment]
@DominatorVbN I also only got this error on the `SettingsView` with the list of contributors, not when creating a new category
Are you able to take a screen recording of you reproducing this?

**Comment by mikaelacaron** [comment]
Closed with #177
