### ISSUE TITLE
Allow user to choose icons for their categories

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#37]
Create a view that allows users to choose from various SFSymbosl to use for the icon of their category, rather than having the default `folder` that's in the app right now

**Comment by mikaelacaron** [comment]
I'm going to "archive" this right now. I'm changing the icons to the SFSymbol for folder, for now.

**Comment by SwiftSergio** [comment]
Please assign this issue to me.

**Comment by mikaelacaron** [comment]
Closes with PR #103
