### ISSUE TITLE
Category folder name label not updated after editing

### ISSUE THREAD

**Issue by lascic** [mikaelacaron/brain-marks#58]
https://user-images.githubusercontent.com/34413704/126882040-cc37bf00-d3b0-46c7-8a37-58343b4a86d5.mp4

While the edited category name actually gets updated, it won't show it unless I restart the app.

**Comment by aerickson14** [comment]
Tried editing a category a few times in a row (10 or so) and it seems to be correctly updating the label every time. It's possible this issue may have gone away with some of the recent updates in the `dev` branch.

**Comment by mikaelacaron** [comment]
Thanks for checking @aerickson14 ! I'll close it for now, it can always be re-opened if it comes back
