### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the marketing version number to the app somewhere that makes sense (maybe adding a settings tab?)

**Describe alternatives you've considered**
Add the version number to the launch screen

**Comment by TiwariPreeti** [comment]
please assign this issue to me

**Comment by mikaelacaron** [comment]
@TiwariPreeti Done! Let me know if you have any issues!
