### ISSUE TITLE
Empty Tweet List View

### ISSUE THREAD

**Issue by NiklasOemler** [mikaelacaron/brain-marks#78]
**Is your feature request related to a problem? Please describe.**
Like the empty list view for categories, id like to request the feature for handling it the same way for the tweet list.

**Describe the solution you'd like**
I can provide a generic empty list view for both lists like in #73. 

Please add the topic Hacktoberfest and assign it to me if you want me to add this feature.
cheers

**Comment by mikaelacaron** [comment]
This looks like it's done "No tweets saved!" shows when you tap on a category with no tweets.
