### ISSUE TITLE
Show Images

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#87]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
If a tweet has an associated image, display that image as well. For this issue focus only on a single image in a tweet, not a tweet with multiple images. (unless that can also be easily added, but I doubt it)

**Describe alternatives you've considered**
N/A

**Additional context**
Example tweet [URL](https://twitter.com/felibe444/status/1450158883088093189?s=20)

**Comment by M1zz** [comment]
sorry I think I can not make it :***(

**Comment by mikaelacaron** [comment]
That's okay! Thanks for trying!

**Comment by frhamadiansyah** [comment]
Hi! can I have a go at it? 😆

**Comment by mikaelacaron** [comment]
@frhamadiansyah Good work!!
Getting the repo ready for Hacktoberfest 2022
